# Generated by Django 4.2.27 on 2025-12-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dictionaryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('dictionary', 'code'), name='unique_dictionary_item_code'),
        ),
    ]
