# Generated by Django 4.2.27 on 2025-12-12 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='Символ')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('indicator_type', models.CharField(choices=[('atomic', 'Атомарный'), ('aggregate', 'Агрегатный')], default='atomic', max_length=20, verbose_name='Тип показателя')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, help_text='Минимальное значение для генерации тестовых данных', max_digits=20, null=True, verbose_name='Минимальное значение')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, help_text='Максимальное значение для генерации тестовых данных', max_digits=20, null=True, verbose_name='Максимальное значение')),
                ('formula', models.TextField(blank=True, help_text='Формула для расчета агрегатного показателя. Используйте названия показателей в квадратных скобках, например: [Показатель1] + [Показатель2] / [Показатель3]', verbose_name='Формула')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='indicators.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('value', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.indicator', verbose_name='Показатель')),
            ],
            options={
                'verbose_name': 'Значение показателя',
                'verbose_name_plural': 'Значения показателей',
                'ordering': ['-date', 'indicator'],
                'unique_together': {('indicator', 'date')},
            },
        ),
    ]
