# Generated by Django 4.2.27 on 2025-12-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='acceptable_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Промежуточное значение (желтый индикатор)', max_digits=20, null=True, verbose_name='Приемлемое значение'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='direction',
            field=models.CharField(choices=[('increasing', 'Растущий'), ('decreasing', 'Снижающийся')], default='increasing', help_text='Растущий - зеленый при росте выше хорошего значения, Снижающийся - зеленый при снижении ниже хорошего значения', max_length=20, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='good_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='При переходе за это значение индикатор будет зеленым', max_digits=20, null=True, verbose_name='Хорошее значение'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='unacceptable_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='При переходе за это значение индикатор будет красным', max_digits=20, null=True, verbose_name='Недопустимое значение'),
        ),
    ]
