# Generated by Django 4.2.27 on 2025-12-12 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0002_indicator_acceptable_value_indicator_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sheet_name', models.CharField(blank=True, help_text='Оставьте пустым для использования первого листа', max_length=100, null=True, verbose_name='Название листа')),
                ('indicator_column', models.CharField(default='M', help_text='Буква колонки (например, M)', max_length=10, verbose_name='Колонка с показателями')),
                ('start_row', models.IntegerField(default=2, help_text='Номер строки, с которой начинаются данные', verbose_name='Строка начала данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('default_unit', models.ForeignKey(blank=True, help_text='Если не указана, будет использована единица "Штука"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.unit', verbose_name='Единица измерения по умолчанию')),
            ],
            options={
                'verbose_name': 'Шаблон импорта',
                'verbose_name_plural': 'Шаблоны импорта',
                'ordering': ['-updated_at'],
            },
        ),
    ]
