# Generated by Django 4.2.27 on 2025-12-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_importtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='value_type',
            field=models.CharField(choices=[('integer', 'Целое'), ('decimal', 'Дробное')], default='decimal', help_text='Целое - значения округляются до целых чисел, Дробное - значения могут быть дробными', max_length=20, verbose_name='Тип значения'),
        ),
    ]
