# Generated by Django 4.2.27 on 2025-12-13 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionaries', '0002_dictionaryitem_unique_dictionary_item_code'),
        ('indicators', '0004_indicator_value_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='indicator',
            name='aggregate_by_dimensions',
            field=models.BooleanField(default=False, help_text='Для агрегатных показателей: если включено, агрегирует только значения с одинаковыми комбинациями справочников. Если выключено, агрегирует все значения независимо от справочников.', verbose_name='Агрегировать в разрезе справочников'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='dictionaries',
            field=models.ManyToManyField(blank=True, help_text='Справочники, в разрезе которых ведется показатель', to='dictionaries.dictionary', verbose_name='Справочники'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='dictionary_required',
            field=models.BooleanField(default=False, help_text='Если включено, каждое значение должно иметь элементы справочников. Если выключено, значения могут быть без разреза.', verbose_name='Обязательность разреза'),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='dictionary_items',
            field=models.ManyToManyField(blank=True, help_text='Элементы справочников для этого значения (разрез)', to='dictionaries.dictionaryitem', verbose_name='Элементы справочников'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='formula',
            field=models.TextField(blank=True, help_text="Формула для расчета агрегатного показателя. Используйте названия показателей в квадратных скобках, например: [Показатель1] + [Показатель2] / [Показатель3]. Для агрегации за период используйте функции: SUM([Показатель], 'month'), AVG([Показатель], 'quarter') и т.д.", verbose_name='Формула'),
        ),
        migrations.CreateModel(
            name='UserDictionaryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='Если включено, пользователь видит только выбранные элементы. Если выключено - может видеть все, но по умолчанию фильтруется.', verbose_name='Обязательный фильтр')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_filters', to='dictionaries.dictionary', verbose_name='Справочник')),
                ('items', models.ManyToManyField(blank=True, help_text='Если пусто и is_required=True - пользователь не видит данные по этому справочнику', to='dictionaries.dictionaryitem', verbose_name='Элементы справочника')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_filters', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фильтр пользователя по справочнику',
                'verbose_name_plural': 'Фильтры пользователей по справочникам',
                'ordering': ['user', 'dictionary'],
                'unique_together': {('user', 'dictionary')},
            },
        ),
    ]
