# Generated by Django 4.2.27 on 2025-12-13 11:13

from django.db import migrations, models
import django.db.models.deletion


def migrate_dictionaries_to_intermediate(apps, schema_editor):
    """Переносим данные из старой ManyToMany связи в промежуточную модель"""
    Indicator = apps.get_model('indicators', 'Indicator')
    IndicatorDictionary = apps.get_model('indicators', 'IndicatorDictionary')
    Dictionary = apps.get_model('dictionaries', 'Dictionary')
    
    # Получаем доступ к старой таблице связи ManyToMany
    db_alias = schema_editor.connection.alias
    
    # Проверяем, существует ли старая таблица связи
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='indicators_indicator_dictionaries'
        """)
        table_exists = cursor.fetchone() is not None
        
        if table_exists:
            # Для каждого показателя с справочниками создаем записи в промежуточной модели
            for indicator in Indicator.objects.using(db_alias).all():
                # Получаем справочники через прямую таблицу связи
                cursor.execute("""
                    SELECT dictionary_id 
                    FROM indicators_indicator_dictionaries 
                    WHERE indicator_id = ?
                """, [indicator.id])
                
                for row in cursor.fetchall():
                    dictionary_id = row[0]
                    IndicatorDictionary.objects.using(db_alias).get_or_create(
                        indicator=indicator,
                        dictionary_id=dictionary_id,
                        defaults={'is_required': False}
                    )


def reverse_migrate(apps, schema_editor):
    """Обратная миграция - не требуется, так как данные будут потеряны"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_dictionaryitem_unique_dictionary_item_code'),
        ('indicators', '0005_alter_indicatorvalue_unique_together_and_more'),
    ]

    operations = [
        # Сначала создаем промежуточную модель
        migrations.CreateModel(
            name='IndicatorDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text='Если включено, каждое значение должно иметь элементы этого справочника. Если выключено, значения могут быть без элементов этого справочника.', verbose_name='Обязательность разреза')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.dictionary', verbose_name='Справочник')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator', verbose_name='Показатель')),
            ],
            options={
                'verbose_name': 'Справочник показателя',
                'verbose_name_plural': 'Справочники показателя',
                'ordering': ['indicator', 'dictionary'],
                'unique_together': {('indicator', 'dictionary')},
            },
        ),
        # Переносим данные
        migrations.RunPython(migrate_dictionaries_to_intermediate, reverse_migrate),
        # Удаляем старое поле
        migrations.RemoveField(
            model_name='indicator',
            name='dictionary_required',
        ),
        # Удаляем старую ManyToMany связь
        migrations.RemoveField(
            model_name='indicator',
            name='dictionaries',
        ),
        # Создаем новую ManyToMany связь с through
        migrations.AddField(
            model_name='indicator',
            name='dictionaries',
            field=models.ManyToManyField(blank=True, help_text='Справочники, в разрезе которых ведется показатель', through='indicators.IndicatorDictionary', to='dictionaries.dictionary', verbose_name='Справочники'),
        ),
    ]
