# Generated by Django 4.2.27 on 2025-12-13 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0006_remove_indicator_dictionary_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, help_text='Если включено, панель видна всем пользователям', verbose_name='Публичная')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Панель визуализации',
                'verbose_name_plural': 'Панели визуализации',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('line', 'Линейный график'), ('bar', 'Столбчатая диаграмма'), ('area', 'Областной график'), ('scatter', 'Точечная диаграмма'), ('pie', 'Круговая диаграмма'), ('gauge', 'Индикатор (gauge)'), ('table', 'Таблица')], default='line', max_length=20, verbose_name='Тип графика')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('days_back', models.IntegerField(default=30, help_text='Сколько дней данных показывать', verbose_name='Дней назад')),
                ('aggregation_period', models.CharField(blank=True, choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц'), ('quarter', 'Квартал'), ('year', 'Год')], default='day', help_text='Если указан, данные будут агрегированы по этому периоду', max_length=20, null=True, verbose_name='Период агрегации')),
                ('show_legend', models.BooleanField(default=True, verbose_name='Показывать легенду')),
                ('show_grid', models.BooleanField(default=True, verbose_name='Показывать сетку')),
                ('height', models.IntegerField(default=400, verbose_name='Высота (px)')),
                ('dictionary_filters', models.JSONField(blank=True, default=dict, help_text='JSON объект с фильтрами по справочникам: {"dictionary_id": [item_id1, item_id2]}', verbose_name='Фильтры по справочникам')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='visualization.dashboard', verbose_name='Панель')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator', verbose_name='Показатель')),
            ],
            options={
                'verbose_name': 'Показатель на панели',
                'verbose_name_plural': 'Показатели на панели',
                'ordering': ['order', 'indicator__name'],
                'unique_together': {('dashboard', 'indicator')},
            },
        ),
    ]
