# Generated by Django 4.2.27 on 2025-12-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardindicator',
            name='cumulative',
            field=models.BooleanField(default=False, help_text='Если включено, значения будут отображаться как нарастающий итог', verbose_name='Нарастающий итог'),
        ),
    ]
